allowBuilds:
  esbuild: true

minimumReleaseAgeExclude:
  - '@vue/compiler-core'
  - '@vue/compiler-dom'
  - '@vue/compiler-sfc'
  - '@vue/compiler-ssr'
  - '@vue/reactivity'
  - '@vue/runtime-core'
  - '@vue/runtime-dom'
  - '@vue/server-renderer'
  - '@vue/shared'
  - vue
