// filepath: src/main.ts
//
// Entry point. Imports UnoCSS's reset (drops browser defaults like button
// borders), then `virtual:uno.css` (on-demand utilities), then the app
// stylesheet, then mounts the Vue app onto `#app` from index.html.
//
// Routing: vue-router 5 built-in file-based routing — pages live in
// `src/pages/` and `routes` is generated by the VueRouter() vite plugin.
// ⚠️ Toy 平台硬约束：必须 hash 模式（createWebHashHistory）。history 模式
// 下刷新 / 直达子路由会 404（页面实际跑在 /toy/<slug>/ 子路径）。

import { createApp } from 'vue'
import { createRouter, createWebHashHistory } from 'vue-router'
import { routes, handleHotUpdate } from 'vue-router/auto-routes'
import '@unocss/reset/tailwind.css'
import 'virtual:uno.css'
import './styles/main.css'
import App from './App.vue'

const router = createRouter({
  history: createWebHashHistory(),
  routes
})

if (import.meta.hot) {
  handleHotUpdate(router)
}

createApp(App).use(router).mount('#app')
