// filepath: src/main.ts
//
// Entry point. Imports UnoCSS's reset (drops browser defaults like button
// borders), then `virtual:uno.css` (on-demand utilities), then the app
// stylesheet, then mounts the Vue app onto `#app` from index.html.
//
// Routing: vue-router 5 built-in file-based routing — pages live in
// `src/pages/` and `routes` is generated by the VueRouter() vite plugin.
// ⚠️ Toy 平台硬约束：必须 hash 模式（createWebHashHistory）。history 模式
// 下刷新 / 直达子路由会 404（页面实际跑在 /toy/<slug>/ 子路径）。

import { createApp } from 'vue'
import { createRouter, createWebHashHistory } from 'vue-router'
import { routes, handleHotUpdate } from 'vue-router/auto-routes'
import { toy } from 'bilibili-toy'
// 业务侧 mock handler 顶层静态 import —— 各文件 (mock/rank.ts 等) 顶层执行
// `rank.override(key).mock(h)`，把 handler 挂到 SDK builder 的 _mock 槽位。
// 这里必须放在 `if (DEV || isPreviewUrl)` 块之前：
//   1. ESM 静态 import 必须是顶层语法（TS1232），不能在 if 块内。
//   2. ESM 顶层 import 是同步求值，副作用在 import 完成时已就位 —— 不会发生
//      "首次 namespace 调用时 mock chunk 还没加载完"的竞态（动态 import 才会拆 chunk）。
//   3. 没有 mock 模式时（prod / 非 preview），handler 注册了也不会被执行：
//      SDK 路由层只在 `mockEnabled && _mock 非空` 时走 mock，否则继续走真实
//      window.toy 路径。所以无条件 import 是安全的。
import '@/mock'
import '@unocss/reset/tailwind.css'
import 'virtual:uno.css'
import './styles/main.css'
import App from './App.vue'

// dev 模式启用 mock：所有 namespace 调用走 mock handler，无 RPC、无握手超时。
// Toy 平台 preview 域名（/toy/preview/<id>/）下 host 故意不注入 toy id，
// SDK 业务能力（getCloudStorage / getRankList / getMyRank 等）会全部 reject，
// 因此 preview 也走 mock，让页面能展示完整业务效果。正式发布（/toy/<slug>/）
// 不会命中此分支，走真实 SDK。
const isPreviewUrl = typeof location !== 'undefined' && location.pathname.includes('/toy/preview/')
if (import.meta.env.DEV || isPreviewUrl) {
  toy.enableMock()
}

const router = createRouter({
  history: createWebHashHistory(),
  routes
})

if (import.meta.hot) {
  handleHotUpdate(router)
}

createApp(App).use(router).mount('#app')
